### PR TITLE
Fixes Read Grammar from File 

### PR DESCRIPTION
**Pull request by apblack**
The menu item to read a grammar form a file was broken.  This fixes that one method.

The other 4 changes are bonus changes generated by git.  Pavel and I spent half an hour trying to figure out where they came from, and failed.  We clone the repository, do nothing, and immediately these file modifications show up in git status.  Feel free to discard them!

### CODE REVIEW

**Comment by ThierryGoubier** [comment]
What have you been using to clone the repository ?

I'm reworking the GUI, I'll integrate this along. Thanks!

**Comment by ThierryGoubier** [comment]
Fix integrated in  cf5c2f1. Thanks!

**Comment by apblack** [comment]
Thanks for accepting the fix.  Pavel and I spend about an hour trying to understand where the other changes were coming form — and failed.  When I cloned the repo (with git clone at the command line), those mods showed up immediately!  Next time I'll try and give you a clean merge.

**Comment by ThierryGoubier** [comment]
Hi @apblack , no worries.

This is strange because I use git clone (command line) to work on SmaCC, and I've never seen that.

**Comment by apblack** [comment]
It’s somethings do with the .gitattributes file, I think ...

**Comment by apblack** [comment]
OK, so Pavel and I just spent another 45 minutes on this, and have a partial explanation.

The issue occurs on Windows and Mac, but not on Linux.  And the one change to a real method involves changing the case of a selector (incorrectly).

Looking closely at this repository, we see pairs of files whose names differ only in the CASE of a letter, e.g., in SmaCC/SmaCC-IDL.package/ASTspecificationNodeVisitor.class/instance/, there are methods visitspecification...2.st and visitSpecification...1.st.   The generated method that changes on checkout on Mac changes the selector of a sent message to `visitspecification:` from `visitSpecification:`.

I don't understand all the details, in particular, I don't understand who generates this method, but it's hard to resist the conclusion that it has to do with case-insensitive file systems like that on the Mac confusing the two files (despite the numeric suffixes).   I guess that if you refactor to remove the method `visitspecification:` with the bad capitalization, then things will be OK again.

As to why this issue shows up only on this repository, I'm guessing that it has to do with the convergence of generated code and case-insensitivity.

**Comment by ThierryGoubier** [comment]
Issue added: #36

**Pull request closed without merging**
