### PR TITLE
Corrects a misconception about the meaning of stream position

### PR DESCRIPTION
**Pull request by apblack**
A misconception about the meaning of position in a stream created an off-by-one error in the tests for LineNumberStream as well as in the code for LineNumberStream>>columnNumber.  This wasn't very noticeable until I started highlighting token ranges in a browser, as well as printing them.

The position of a stream is the index of the most-recently-read character.  Initially, a stream is at position 0.  _After_ reading one character, it is at position 1, and so on.  The column number of a stream must therefor be initially 0, and it becomes 1 only after reading the first character of the stream, and subsequently after reading the first character of a line.

If the most recently-read character is (one of) the newline character(s), then the column position must be 0.

I hope that this commit clarifies the tests, as well as adapting them so that the correct code passes the tests.

### CODE REVIEW

**Comment by ThierryGoubier** [comment]
Hi @apblack , why are you changing SmaCC-Runtime as well?

**Comment by apblack** [comment]
Because it was wrong!  See the comment in the method that returns the columnNumber from a stream position.

**Comment by ThierryGoubier** [comment]
My mistake: my question was about the fact you were also changing the error reporting, and that it doesn't seem to be related.

**Comment by apblack** [comment]
Thanks for merging.  I didn't think that I was changing the error reporting.  I _am_ doing so in my private branch, but that should not have been part of the Pull request.   It was _not_ in the final version, but perhaps I included it by mistake in an earlier version.

**Pull request merged**
